logging:
  level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management.endpoints.web.exposure.include: "*"

server:
  port: 8080

springdoc.api-docs.path: /api-docs

challenge.rest.endpoint: https://challenge-business-sector-api.meza.talkdeskstg.com
challenge.rest.sector: /sector/
file.prefix.name: prefixes.txt